### PR TITLE
Setup docker-compose for local development

### PR DESCRIPTION
**Pull request by deekim**
and _add_ a developer's guide

---

First off, thanks for creating and maintaining such an awesome tool!

@csandersdev and I were interested in playing around with the codebase locally and 
ended up creating some docs and scripts that we thought might be useful to the broader community.

### CODE REVIEW

**Comment by mik-ohdsi** [comment]
Hi there, we do not really encourage building and running a local Athena for one obvious reason: it is meant to be a central instance for browsing but more importantly distributing consistent vocabulary downloads to the OHDSI community. Use cases for running it locally have not yet been convincing enough to justify the effort. What are your use cases? - cheers ~ Mik

**Comment by deekim** [comment]
Hi @mik-ohdsi,

It would be primarily for ease of local development.
It lowers the barrier for external contributors not familiar with the technology stack to make changes to the codebase.

I understand your concerns and will close this PR accordingly.

Appreciate your feedback.

**Comment by mik-ohdsi** [comment]
not so fast, @deekim ! :-)
your use case is valid if you want to have a local dev instance. Actually, the first time someone brought this use case forward and indicated interest in collaborating on Athena!
We have plenty of stuff to fix and more to enhance, but so little hands... I am myself the lead for the vocabularies but have not a lot of stakes in Athena besides being responsible for what is in it... so, I did not want to discourage you, on the contrary!

**Comment by deekim** [comment]
Whoops :)

Happy to try to work with whoever to merge this back if you'd like.
I'm a bit busy over the next few weeks, so it might take me a bit to resolve any issues.
Thanks for considering the contribution.

**Pull request closed without merging**
